### ISSUE TITLE
Wild and Free Undefined

### ISSUE THREAD

**Issue by Sparkrdom** [thehajo/VokriinatorBlack#1]
The Wild and Free perk in Light Armor is showing as Undefined for level 2

![image](https://user-images.githubusercontent.com/22569083/135741640-e925af54-5169-4147-b9d7-78b2ec3d0215.png)
![image](https://user-images.githubusercontent.com/22569083/135741646-100e91da-9fa2-49eb-a82f-2690f3c9adce.png)

**Comment by thehajo** [comment]
Whoops, missed that one. I blame the fact that the second level perk is actually called Evasive Leap. Either way, fixed for this and PotD. Thanks!
